### PR TITLE
Random crash header shows correct developer

### PR DESCRIPTION
**Pull request by TheIcyOne**

### CODE REVIEW

**Comment by hadn69** [comment]
I am completely in love with this!!

**Comment by ZombieHDGaming** [comment]
Not even gonna bother with this.

**Comment by Growlith1223** [comment]
pls

**Comment by Rongmario** [comment]
Don't respond to circlejerks and get baited.

I thought you were better than this @TheIcyOne.

**Comment by TheIcyOne** [comment]
@Andromander The point of said message is at best lost on the average end user and at worst actively damaging to the stability and development of other mods. This PR acts to prevent unnecessary confusion resulting from this ill-conceived joke, by sending those users who do come across it to somebody willing to pass their crash reports to the correct person.

**Comment by Drullkus** [comment]
smh

**Comment by Rongmario** [comment]
TheRetardOne, stop.

**Pull request closed without merging**
