### PR TITLE
Update to 1.17.1

### PR DESCRIPTION
**Pull request by triphora**
A number of things (including the headlining 3x FPS boost feature) are missing/commented out, but the game launches and can load into a world just fine.

I do plan on trying to get the commented out things working again, but I'm burnt out from 3 hours of  work straight on getting it loading into a world, so I'm not going to do it right now. :P

If someone else wants to help out, feel free to push to my 1.17 branch, I've allowed edits by maintainers.

### CODE REVIEW

**Review by BoogieMonster1O1 — COMMENTED** [review]
Looks pretty good. Can you add TODOs to the comments? Might help ides find what code is still to be implemented

**Comment by triphora** [comment]
Did that with FIXMEs. IntelliJ renders FIXMEs identically to TODOs.

**Comment by AnErrupTion** [comment]
Any progress yet? I really want VanillaFix for 1.17 Fabric :p

**Comment by Mysticpasta1** [comment]
So just checking on this... How is it going?

**Comment by triphora** [comment]
I mentioned in the Discord a couple times that I wasn't going to be working on this because I didn't know how to. Anyone else can feel free to work on this.

**Pull request closed without merging**
